package models.composants;

public enum EMRTypes {
    ENERGY_SOURCE, ACCUMULATION,CONVERSION,COUPLING,INVERSION_CONVERSION_INVERSION_ACCUMULATION,
    INVERSION_COUPLING, AMPLIFICATION, CONTROL_STRATEGY
}
